[gcloud]
disabled = true

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[package]
format = '[📦 $version](208 bold) '

[java]
disabled = true

[kotlin]
format = "[${symbol} ]($style)"

[gradle]
disabled = true

[nodejs]
format = "[${symbol} ]($style)"

[rust]
format = "[${symbol} ]($style)"
