# Starship configuration file
# Configuration page: https://starship.rs/config/
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

character.success_symbol = "[ ➜](bold green)"
character.error_symbol = "[ ➜](bold red)"

gradle.disabled = true
java.disabled = true 
